site_name: lernOS Leadership Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen: 1-Grundlagen.md
    - Lernpfad: 2-Lernpfad.md
    - Anhang: 3-Anhang.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-Leadership-Guide-de.pdf
      - Word-Version: https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-Leadership-Guide-de.docx
      - HTML-Version: https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-Leadership-Guide-de.html
      - E-Book (epub): https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-Leadership-Guide-de.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-Leadership-Guide-de.mobi
    - Links:
      - lernOS Website: https://lernos.org
      - lernOS Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-leadership'
repo_url: 'https://github.com/cogneon/lernos-leadership'

extra:
#    social:
#        - type: 'twitter'
#          link: 'https://twitter.com/lern_os'
#        - type: 'linkedin'
#          link: 'https://www.linkedin.com/showcase/lern-os'
#        - type: 'github'
#          link: 'https://github.com/cogneon'
    disqus: lernos
